import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import routes from './routes.js';
const app=express();
app.use(helmet());
app.use(cors({origin:process.env.CLIENT_ORIGIN?.split(',')||'http://localhost:5173'}));
app.use(express.json({limit:'1mb'}));
app.use(rateLimit({windowMs:60_000,limit:120,standardHeaders:'draft-7',legacyHeaders:false}));
app.get('/api/health',(req,res)=>res.json({ok:true,service:'anacity-agentic-api'}));
app.use('/api',routes);
export default app;
